In [1]:
import numpy as np
import pandas as pd

In [2]:
years = ['2021-12-31', '2022-12-31', '2023-12-31', '2024-12-31', '2025-12-31', '2026-12-31', '2027-12-31', '2028-12-31', '2029-12-31', '2030-12-31', '2031-12-31', '2032-12-31']
Revenue = pd.Series(index=years, dtype ='float64')
Revenue['2021-12-31'] = 222  
Revenue

2021-12-31    222.0
2022-12-31      NaN
2023-12-31      NaN
2024-12-31      NaN
2025-12-31      NaN
2026-12-31      NaN
2027-12-31      NaN
2028-12-31      NaN
2029-12-31      NaN
2030-12-31      NaN
2031-12-31      NaN
2032-12-31      NaN
dtype: float64

In [3]:
growth_rate = 0.18
for year in range(1, 12):
    Revenue[year] = Revenue[year - 1] * (1 + growth_rate)  
ebitda_margin = 0.45
EBITDA = Revenue * ebitda_margin
tax_rate = 0.21
Tax = -EBITDA * tax_rate 
Capital_Expenditures_rate = 0.03
Capital_Expenditures = -Capital_Expenditures_rate * Revenue 
Working_Capital_rate = 0.06
Working_Capital = -Working_Capital_rate * Revenue 
Cash_Flow = EBITDA + Tax + Capital_Expenditures + Working_Capital
Discount_rate = 0.06
Discount_factor = pd.Series(index = years, dtype='float64')
for year in range(0,12):
    Discount_factor[year]= (1 - Discount_rate) ** year
Present_Value_FCF = (Discount_factor * Cash_Flow)

In [4]:
output = pd.DataFrame(index = years , columns =['Revenue', 'EBITDA', 'Tax', 'Capital_Expenditures', 'Working_Capital', 'Cash_Flow', 'Discount_Factor', 'Present_Value_FCF'])
output['Revenue']=Revenue
output['EBITDA']= EBITDA
output['Tax']= Tax
output['Capital_Expenditures']=Capital_Expenditures
output['Working_Capital']=Working_Capital
output['Cash_Flow'] = Cash_Flow
output['Discount_Factor']= Discount_factor
output['Present_Value_FCF']=Present_Value_FCF
output

,Revenue,EBITDA,Tax,Capital_Expenditures,Working_Capital,Cash_Flow,Discount_Factor,Present_Value_FCF
2021-12-31,222.000000,99.900000,-20.979000,-6.660000,-13.320000,58.941000,1.000000,58.941000
2022-12-31,261.960000,117.882000,-24.755220,-7.858800,-15.717600,69.550380,0.940000,65.377357
2023-12-31,309.112800,139.100760,-29.211160,-9.273384,-18.546768,82.069448,0.883600,72.516565
2024-12-31,364.753104,164.138897,-34.469168,-10.942593,-21.885186,96.841949,0.830584,80.435373
2025-12-31,430.408663,193.683898,-40.673619,-12.912260,-25.824520,114.273500,0.780749,89.218916
2026-12-31,507.882222,228.547000,-47.994870,-15.236467,-30.472933,134.842730,0.733904,98.961622
2027-12-31,599.301022,269.685460,-56.633947,-17.979031,-35.958061,159.114421,0.689870,109.768231
2028-12-31,707.175206,318.228843,-66.828057,-21.215256,-42.430512,187.755017,0.648478,121.754922
2029-12-31,834.466743,375.510034,-78.857107,-25.034002,-50.068005,221.550920,0.609569,135.050559
2030-12-31,984.670757,443.101841,-93.051387,-29.540123,-59.080245,261.430086,0.572995,149.798080
2031-12-31,1161.911493,522.860172,-109.800636,-34.857345,-69.714690,308.487501,0.538615,166.156031
2032-12-31,1371.055562,616.975003,-129.564751,-41.131667,-82.263334,364.015252,0.506298,184.300269

In [5]:
pv = output.Present_Value_FCF[1:-1].sum()
terminal_value = 32.7 * output.EBITDA[-1]
present_value_of_terminal_value = terminal_value * output.Discount_Factor[-2]
present_value_of_asset = pv + present_value_of_terminal_value
print('Our projected Present Value of Projected Future Cash Flows are:', str(output.Present_Value_FCF[1:-1].sum()) )
print('We are providing revenue guidance in 2032 to be:',  str(Revenue[11]) )
print('With an estimated EBITDA around:', str(EBITDA[11]) )
print('The terminal value at this time given a multiple of 32.7 and the above EBITDA for 2032, would equal:' +  str(present_value_of_terminal_value))
print('The present value of asset:', str(present_value_of_asset))

Our projected Present Value of Projected Future Cash Flows are: 1089.037656673089
We are providing revenue guidance in 2032 to be: 1371.055561673072
With an estimated EBITDA around: 616.9750027528823
The terminal value at this time given a multiple of 32.7 and the above EBITDA for 2032, would equal:10866.604411097238
The present value of asset: 11955.642067770326